### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Callable' when running python PyIris.py for the first time

### ISSUE THREAD

**Issue by dimani128** [angus-y/PyIris-backdoor#31]
## Step 1 : Environment information where PyIris was run
- Exact OS Version: Windows 11 (10.0.22000 Build 22000)
- PyIris Version: Latest
- Python Version: 3.10.6

## Step 2 : What was done before the error
- What commands were ran before the error: Initial run of ```python PyIris.py ```
- What was the state of the framework before the error (eg. How many listeners active, how many scouts connected, etc.): None
- Programs running while PyIris was running: Command Prompt (where it was running), Edge, File Explorer
- What was modified in the framework files (If any were modified): Nothing

## Step 3 : Evidence and description
- Description of the error: Ran ```python PyIris.py``` for the first time and got the error: ``` AttributeError: module 'collections' has no attribute 'Callable' ```
- Raw text of the error:
```[*]Starting...
[+]Using Python Version 3 - OK
[+]All local files imported - OK
[+]OS Windows - OK
[+]Successfully imported : pyperclip - OK
[+]Successfully imported : win32crypt - OK
[+]Successfully imported : cv2 - OK
[+]Successfully imported : pythoncom - OK
[+]Successfully imported : mss - OK
[+]Successfully imported : PIL - OK
[+]Successfully imported : pyautogui - OK
[+]Successfully imported : colorama - OK
[+]Successfully imported : cryptography - OK
[+]Successfully imported : pyWinhook - OK
[+]Successfully imported : pycaw - OK
CRITICAL:root:Unexpected error when bootstrapping, dumping stack trace and exiting...
Traceback (most recent call last):
  File "C:\Users\danie\Documents\Python\PyIris\library\modules\bootstrap.py", line 33, in main
    exec ('import ' + i)
  File "<string>", line 1, in <module>
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

## Step 4 : Miscellaneous information
- Any miscellaneous information you would like to provide, the more data provided the better: Removed package versions from requirements.txt because the specified versions couldn't be found.

**Comment by not-sekiun** [comment]
Hi, ive been working on pyiris 3.0 on a private repository so the current major version you are using (the one which is publicly available), 2.0 has not been updated for the latest version of python. This error is caused by some changes in python 3.10 to the collections module which breaks the framework. **As of now, python 3.10 is not supported for pyiris, use an older version of python like 3.9/3.8/3.7**. Because 3.10 is so relatively new, some of the packages that pyiris requires are not yet ported to 3.10 hence why you had to remove some packages from the requirements.txt file and why it errored out so badly

**Comment by dimani128** [comment]
Got it.
